### PR TITLE
added -nofocus variant of all methods

### PR DESCRIPTION
**Pull request by dsbauer**
I needed to manipulate text selections without setting focus on the text element, and this seemed the best solution for adding that variant while remaining fully backward compatible.
Please consider merging this addition into the main package or implementing this feature by other means.  Thanks!

### CODE REVIEW

**Comment by imhoffd** [comment]
Thanks for the PR! I may take a look at re-implementing this with an options object as a second, optional parameter to each method. 

As best practice for future PRs, please refrain from updating version numbers--the maintainer will release the software. 👍

**Comment by dsbauer** [comment]
A fair point; understood and agreed, thanks.  I'll look forward to adopting your update when ready.

**Comment by imhoffd** [comment]
@dsbauer Does this suit your needs? https://github.com/dwieeb/jquery-textrange#options

`1.4.0` is out.

**Comment by dsbauer** [comment]
Thanks for adding the `nofocus` option!  Your solution (`{...,nofocus:true}`) works for me.  It might be slightly cleaner conceptually to use implied `{focus:true}` as the default, with `{focus:false}` as the exception, but taste varies.
Depending on future additional options, another choice might be to allow multiple non-numeric string options after the first argument (method name), as in: `textrange('set','nofocus',0,0)` or `textrange('get','nofocus','please','length')`.  But I'm good now, thanks.

**Pull request closed without merging**
